import type { Assembly, System } from './types';
export const systems: System[] = [
  {
    id: 'structure',
    name: 'Structure & floors',
    short: 'Structure',
    description: 'A concrete frame around a generous central void.',
  },
  {
    id: 'facade',
    name: 'Façade & glazing',
    short: 'Façade',
    description: 'Repeated glazed bays and an exposed structural rhythm.',
  },
  {
    id: 'services',
    name: 'Service towers',
    short: 'Services',
    description: 'Six perimeter towers make the building’s workings visible.',
  },
  {
    id: 'circulation',
    name: 'Lifts, stairs & escalators',
    short: 'Circulation',
    description: 'External vertical routes and interior connections.',
  },
  {
    id: 'roof',
    name: 'Atrium & roof',
    short: 'Atrium',
    description: 'A glass vault above the central space.',
  },
  {
    id: 'room',
    name: 'Underwriting Room',
    short: 'The Room',
    description: 'An illustrative setting for face-to-face negotiation.',
  },
  {
    id: 'heritage',
    name: 'Heritage features',
    short: 'Heritage',
    description: 'Historic objects within a modern architectural setting.',
  },
];
export const assemblies: Assembly[] = [
  {
    id: 'columns',
    name: 'Concrete columns & capitals',
    system: 'structure',
    description: 'Columns and beams support the galleries around the atrium.',
    significance: 'The visible frame gives the large interior a legible structure.',
    accuracy: 'Approximate',
    sources: ['rshp'],
  },
  {
    id: 'bracing',
    name: 'External cross-bracing',
    system: 'structure',
    description: 'Diagonal members articulate the outside of the frame.',
    significance: 'Their position expresses how the building is supported.',
    accuracy: 'Approximate',
    sources: ['rshp'],
  },
  ...Array.from(
    { length: 12 },
    (_, i): Assembly => ({
      id: `floor-${i}`,
      name: i === 0 ? 'Ground · Underwriting floor' : `Gallery ${String(i).padStart(2, '0')}`,
      system: 'structure',
      description: 'Gallery floor plates surround the open central atrium.',
      significance:
        'Spaces can adapt as the market’s needs change. Level labels here organise the model; boundaries are approximate.',
      accuracy: 'Approximate',
      sources: ['rshp'],
    }),
  ),
  {
    id: 'curtain-wall',
    name: 'Glazed façade bays',
    system: 'facade',
    description: 'The glazing forms a layered environmental envelope.',
    significance:
      'The original design used the glazing as part of the air-handling strategy. Panels here simplify that construction.',
    accuracy: 'Approximate',
    sources: ['rshp'],
  },
  {
    id: 'mullions',
    name: 'Mullions & maintenance galleries',
    system: 'facade',
    description: 'A repeating grid gives the elevations their fine grain.',
    significance: 'Visible rails and frames help reveal the building’s many layers.',
    accuracy: 'Approximate',
    sources: ['rshp'],
  },
  ...['North-west', 'North-east', 'South-west', 'South-east', 'Southern west', 'Southern east'].map(
    (n, i): Assembly => ({
      id: `tower-${i}`,
      name: `${n} service tower`,
      system: 'services',
      description: 'Perimeter towers accommodate the building’s services.',
      significance:
        'Keeping services outside frees up the interior. These positional names are model labels, not official tower designations.',
      accuracy: 'Approximate',
      sources: ['rshp'],
    }),
  ),
  {
    id: 'service-pods',
    name: 'Prefabricated service pods',
    system: 'services',
    description: 'Projecting rectangular service enclosures sit beside the curved stairs.',
    significance:
      'Individual pods, portholes and their supporting framework are interpreted from the supplied close-up references; their internal fit-out is not modelled.',
    accuracy: 'Approximate',
    sources: ['rshp'],
  },
  {
    id: 'pipework',
    name: 'Exposed ducts & risers',
    system: 'services',
    description: 'External pipes make servicing visible and accessible.',
    significance: 'Routes are simplified from photographs, not an engineering services survey.',
    accuracy: 'Approximate',
    sources: ['lloyds'],
  },
  {
    id: 'plant',
    name: 'Rooftop plant rooms',
    system: 'services',
    description: 'Four large steel-clad plant rooms crown the taller service towers.',
    significance: 'Their varied heights contribute to the distinctive silhouette.',
    accuracy: 'Approximate',
    sources: ['rshp'],
  },
  {
    id: 'lifts',
    name: 'External glass lifts',
    system: 'circulation',
    description: 'Lloyd’s has twelve external glass lifts.',
    significance:
      'Glazed lift cars turn movement into part of the elevation. This model uses representative positions.',
    accuracy: 'Approximate',
    sources: ['lloyds'],
  },
  {
    id: 'stairs',
    name: 'Stainless-steel stair enclosures',
    system: 'circulation',
    description: 'Stairs provide routes between levels at the perimeter.',
    significance: 'Stacked curved enclosures are a signature of the inside-out architecture.',
    accuracy: 'Approximate',
    sources: ['rshp'],
  },
  {
    id: 'escalators',
    name: 'Central escalators',
    system: 'circulation',
    description: 'Escalators link the lower trading levels across the atrium.',
    significance:
      'Their open arrangement makes movement between galleries visible. Routes and step counts are illustrative.',
    accuracy: 'Illustrative',
    sources: ['rshp'],
  },
  {
    id: 'vault',
    name: 'Barrel-vaulted glass roof',
    system: 'roof',
    description: 'The steel-and-glass vault brings daylight into the atrium.',
    significance: 'A light lattice spans above the heavier concrete structure.',
    accuracy: 'Approximate',
    sources: ['lloyds'],
  },
  {
    id: 'end-screen',
    name: 'Atrium end screens',
    system: 'roof',
    description: 'Tall glazed ends continue the roof’s slender framework.',
    significance: 'These simplified screens reveal the vertical extent of the atrium.',
    accuracy: 'Approximate',
    sources: ['rshp'],
  },
  {
    id: 'cranes',
    name: 'Blue maintenance cranes',
    system: 'roof',
    description: 'Permanent rooftop cranes support exterior maintenance.',
    significance: 'They make the building’s continued care visible on its skyline.',
    accuracy: 'Approximate',
    sources: ['lloyds'],
  },
  {
    id: 'boxes',
    name: 'Representative underwriting boxes',
    system: 'room',
    description: 'Brokers meet underwriters at desks known as boxes.',
    significance:
      'These invented furnishings explain the use of the space. They do not show current desk allocations.',
    accuracy: 'Illustrative',
    sources: ['room'],
  },
  {
    id: 'room-lights',
    name: 'Coffered lighting grid',
    system: 'room',
    description: 'Ceiling lights in the building also serve as air extractors.',
    significance:
      'The model suggests the ceiling rhythm without reproducing its technical details.',
    accuracy: 'Illustrative',
    sources: ['lloyds'],
  },
  {
    id: 'rostrum',
    name: 'The Rostrum & Lutine Bell',
    system: 'heritage',
    description: 'The mahogany Rostrum holds the historic Lutine Bell.',
    significance:
      'This simplified representation marks a link between the market’s history and its modern home.',
    accuracy: 'Illustrative',
    sources: ['lloyds'],
  },
];
export const assemblyById = new Map(assemblies.map((a) => [a.id, a]));
